# Generated by Django 6.0.3 on 2026-03-07 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categorie_options_categorie_date_creation'),
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['nom'], 'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicaments', to='categories.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dci',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='DCI'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom commercial'),
        ),
    ]
